services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    #volumes:
    #  - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8888:8080
